altproduct/urls.py
""" URLs file """

from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views
from .views import CustomLoginView

app_name = "altproduct"

urlpatterns = [
    path('', views.index, name='index'),
    path('mentions-legales/', views.legal, name='legal'),
    path('creer-compte/', views.register, name='register'),
    path('connexion/', CustomLoginView.as_view(), name='account_login'),
    path('deconnexion/', LogoutView.as_view(), name='logout'),
    path('mon-compte/', views.account, name='account'),
    path('alternatives/', views.alternative, name='alternative'),
    path('alternatives/save_product/', views.save_product, name='save_product'), # Ajax view
    path('produit-alternatif/<str:product_id>/<str:product_name>/', views.product_detail, name='product_detail'),
    path('mes-produits/', views.fav_products, name='fav_products'),
    path('contact/', views.thanks, name='thanks'),
    path('erreur/', views.error, name='error'),
    path('activation/<int:account_id>/', views.account_activation, name='activation'),
]

vegalt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('altproduct.urls')),
]

altproduct/models.py
""" Models declaration """

from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """ Product category model. Consider that there is only one category per product. """

    name = models.CharField(max_length=50)
    alternative = models.BooleanField(default=None)

    def __str__(self):
        return self.name


class Brand(models.Model):
    """ Brand model. One brand per product. """

    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Store(models.Model):
    """ Store model. One store per product. """

    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class NutriGrade(models.Model):
    """ Nutrigrade model. Enum type. """

    NUTRIGRADE_CHOICES = (
        ('a', 'A'),
        ('b', 'B'),
        ('c', 'C'),
        ('d', 'D'),
        ('e', 'E'),
    )

    nutrigrade = models.CharField(max_length=1, choices=NUTRIGRADE_CHOICES)

    def __str__(self):
        return self.nutrigrade


class Product(models.Model):
    """ Product model. This is the main model : it has link with all other models. """

    name = models.CharField(max_length=200)
    description = models.TextField(max_length=200)
    link = models.URLField()
    image = models.URLField()
    nutrition_image = models.URLField()
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    brand = models.ForeignKey(Brand, on_delete=models.DO_NOTHING)
    store = models.ForeignKey(Store, on_delete=models.DO_NOTHING)
    nutrigrade = models.ForeignKey(NutriGrade, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class FavouriteProduct(models.Model):
    """ Favourite product model. Reference table between Product and User. """

    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

altproduct/forms.py
""" Forms file """

from django.forms import (
    ModelForm, EmailInput, PasswordInput, ValidationError, Form, CharField, TextInput, Textarea, BooleanField, EmailField
)
from django.contrib.auth.models import User


class RegisterForm(ModelForm):
    """ Form to create an account. Based on Django User model. """

    class Meta:
        """ Get the Django User attributes. """

        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'email': EmailInput(),
            'password': PasswordInput()
        }

    def clean_email(self):
        """
        Force verification to have unique email per account. Not by default on User Django model.
        """

        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exists():
            raise ValidationError(u'Un utilisateur avec cette adresse email existe déjà.')

        return email


class SearchForm(Form):
    """ Form to search a product alternative. Display on nav and index page. """

    product = CharField(
        max_length=200,
        widget=TextInput(attrs={
            'placeholder': 'Entrez le produit que vous voulez remplacer',
            })
    )

    def add_prefix(self, field_name):
        """ Custom field name to have the URL parameter in FR """

        field_name = "produit"
        return super(SearchForm, self).add_prefix(field_name)


class ContactForm(Form):
    """ Form to contact site owners. Display on index page. """

    name = CharField(
        widget=TextInput(attrs={
            'placeholder': 'Nom',
            'class': 'contact-name',
        }))

    sender_mail = EmailField(
        widget=TextInput(attrs={
            'placeholder': 'Email',
            'class': 'contact-mail',
        }))

    message = CharField(
        widget=Textarea(attrs={
            'placeholder': 'Message',
            'rows': 5,
            'class': 'form-control',
        }))

altproduct/views.py
""" Views file """

import json
from smtplib import SMTPException

from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from vegalt import settings
from .forms import RegisterForm, SearchForm, ContactForm
from .models import Product, Category, FavouriteProduct


def index(request):
    """
    Home route with contact form management. 
    Send plain message for site owner and html message for client.
    """

    context = {
        'search_form': SearchForm(),
    }

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)

        if contact_form.is_valid():
            name = contact_form.cleaned_data['name']
            sender_mail = contact_form.cleaned_data['sender_mail']
            message = contact_form.cleaned_data['message']

            # Create email content for site owner
            subject_to_site = "Vegalt : Nouvelle demande de contact"
            plain_message_to_site = "Bonjour Vegalt,\n\nVoici un nouveau message de " + name + "<" + sender_mail + "> :\n\n" + message + "\n\nRépondez-lui rapidement !"

            # Create confirmation email for sender
            subject_to_sender = "Vegalt : Message reçu 5/5 !"
            content_to_sender = "L'équipe de Vegalt a bien reçu votre message. On pédale fort pour vous répondre le plus rapidement possible !"
            signature_to_sender = "A bientôt sur Vegalt !"

            # Create the html message
            html_message_to_sender = render_to_string('mail.html', {
                'username': name,
                'content': content_to_sender,
                'signature': signature_to_sender,
            })
            plain_message_to_sender = strip_tags(html_message_to_sender)

            # Set mails settings
            from_mail = to_site_mail = 'vegalt@ovh.fr'
            to_sender_mail = sender_mail

            try:
                # Send contact to site owner
                send_mail(
                    subject=subject_to_site,
                    message=plain_message_to_site,
                    from_email=from_mail,
                    recipient_list=[to_site_mail],
                    fail_silently=False
                )

                # Send confirmation email to sender
                send_mail(
                    subject=subject_to_sender,
                    message=plain_message_to_sender,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[to_sender_mail],
                    fail_silently=False,
                    html_message=html_message_to_sender
                )

                return redirect('altproduct:thanks')

            except SMTPException:
                return redirect('altproduct:error')

    else:
        contact_form = ContactForm()

    context['h1_tag'] = 'Du gras oui, mais de qualité !'
    context['contact_form'] = contact_form

    return render(request, 'altproduct/index.html', context)


def thanks(request):
    """ Thanks route after contact form submission. """

    context = {
        'search_form': SearchForm(),
        'h1_tag': 'Reçu 5/5 !',
    }

    return render(request, 'altproduct/thanks.html', context)


def error(request):
    """ Error page if a SMTP error is raised after mail sending. """

    context = {
        'search_form': SearchForm(),
        'h1_tag': 'On a un problème Houston',
    }

    return render(request, 'altproduct/error.html', context)


def legal(request):
    """ Legal route. """

    context = {
        'h1_tag': 'Mentions légales',
        'search_form': SearchForm(),
    }
    return render(request, 'altproduct/legal.html', context)


def register(request):
    """ Account creation route. Send an email to activate the account."""

    context = {
        'h1_tag': 'Créer un compte',
        'h2_tag': 'Un nom, un mot de passe et c\'est parti !',
        'search_form': SearchForm(),
    }

    # If the register form is posted
    if request.method == "POST":

        register_form = RegisterForm(request.POST)

        # Verify all datas posted
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            email = register_form.cleaned_data['email']
            password = register_form.cleaned_data['password']

            # Create the new user in database if it's not existing
            user = User.objects.filter(email=email)
            if not user.exists():
                user = User.objects.create_user(username, email=email, password=password)
                # User needs to activate his account
                user.is_active = False
                user.save()

                # Create an account activation mail
                subject = "Vegalt : Activez votre compte fraîchement créé !"
                content = "Veuillez confirmer votre mail et activer votre compte en cliquant sur le lien suivant :"
                signature = "A bientôt sur Vegalt !"

                # Get domain name for activation link
                protocol = "http://" # To be changed on prod by https ?
                host = request.get_host()

                # Create the message
                html_message = render_to_string('mail.html', {
                    'username': username,
                    'content': content,
                    'protocol': protocol,
                    'host': host,
                    'account_id': user.id,
                    'signature': signature
                })
                plain_message = strip_tags(html_message)

                # Set mails settings
                to_mail = email

                send_mail(
                    subject=subject,
                    message=plain_message,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[to_mail],
                    html_message=html_message
                )

                return redirect('altproduct:account_login')

        else:
            context['errors'] = register_form.errors.items()

    # If not, create the empty register form
    else:
        register_form = RegisterForm()

    context['register_form'] = register_form

    return render(request, 'altproduct/account.html', context)


def account_activation(request, account_id):
    """ Account activation route. Set the is_active field from User model to True. """

    user = User.objects.get(pk=account_id)
    user.is_active = True
    user.save()

    context = {
        'h1_tag': 'Activation de votre compte',
        'username': user.username,
    }

    return render(request, 'altproduct/activation.html', context)


class CustomLoginView(LoginView):
    """ Subclass from Django LoginView. Personnalized account login route. """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'h1_tag': 'Connexion à votre compte',
            'h2_tag': 'Entrez vos identifiants de connexion pour accéder à votre compte',
            'search_form': SearchForm(),
            'next': reverse_lazy('altproduct:account')
        })

        return context


def account(request):
    """ Account route """

    context = {
        'h1_tag': 'Ahoy',
        'h2_tag': 'Paramètres de votre compte',
        'search_form': SearchForm(),
    }

    return render(request, 'altproduct/account.html', context)


def alternative(request):
    """ Alternative route, when a product is searched """

    searched_product = request.GET.get('produit')
    user = request.user

    context = {
        'h1_tag': searched_product,
        'search_form': SearchForm(),
        'searched_product': searched_product,
    }

    try:
        category = Category.objects.get(name__icontains=searched_product, alternative=False)
        product = Product.objects.filter(category_id=category.id).order_by('?')[1]

        context['searched_product_img'] = product.image
        context['h2_tag'] = 'Vous pouvez remplacer cet aliment par :'

        categories = Category.objects.filter(name__icontains=searched_product, alternative=True)

        # Isolate products registered by the user
        if user:
            fav_products = FavouriteProduct.objects.filter(user_id=user.id)
            fav_products_id = [fav_product.product_id for fav_product in fav_products]

        products = []
        for category in categories:
            # Get all products by category, excluding products registered
            products_per_category = Product.objects.filter(category_id=category.id).exclude(id__in=fav_products_id)

            for product in products_per_category:
                # Keep FR products
                if product not in products and not 'Hamburguesa' in product.name and not 'Bebida' in product.name:
                    products.append(product)

        if not products:
            context['h2_tag'] = 'Aucun produit alternatif n\'a été trouvé :('
            context['message'] = 'Essayez une nouvelle recherche avec un autre produit.'

        else:
            paginator = Paginator(products, 9)
            page = request.GET.get('page')
            alt_products = paginator.get_page(page)

            context['alt_products'] = alt_products
            context['paginate'] = True

    except Category.DoesNotExist:
        context['h2_tag'] = 'Votre recherche n\'a retourné aucun résultat'
        context['message'] = 'Essayez une nouvelle recherche avec un autre produit.'

    return render(request, 'altproduct/alternative.html', context)


def product_detail(request, product_id, product_name):
    """ Product detail route. """

    # Get product by id, because many products can have the same name

altproduct/templates/altproduct/account.html
{% extends 'altproduct/base.html' %}

{% block content %}

{% include 'altproduct/little-header.html' %}

<section id="account">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">

                <h2 class="section-heading">{{ h2_tag }}</h2>
                <hr class="my-4">

                {% if register_form %}
                <form id="account-form" action="{% url 'altproduct:register' %}" method="POST" class="mt-50">
                    {% csrf_token %}

                    {{ register_form.non_field_errors }}
                    <div class="fieldWrapper">
                        <label for="{{ register_form.username.id_for_label }}">Nom d'utilisateur</label>
                        {{ register_form.username }}
                        {% if register_form.username.errors %}
                            {% for error in register_form.username.errors %}
                                <p class="errorform">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="fieldWrapper">
                        <label for="{{ register_form.email.id_for_label }}">Adresse email</label>
                        {{ register_form.email }}
                        {% if register_form.email.errors %}
                            {% for error in register_form.email.errors %}
                                <p class="errorform">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="fieldWrapper">
                        <label for="{{ register_form.password.id_for_label }}">Mot de passe</label>
                        {{ register_form.password }}
                        {% if register_form.password.errors %}
                            {% for error in register_form.password.errors %}
                                <p class="errorform">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <input type="submit" value="Créer mon compte" class="btn btn-primary btn-xl js-scroll-trigger mt-50">
                </form>

                {% else %}
                    <p>Voici l'adresse mail rattachée à votre compte :</p>
                    <p class="alert alert-secondary account-email">{{ user.email }}</p>

                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

altproduct/templates/altproduct/alternative.html
{% extends 'altproduct/base.html' %}

{% block content %}

{% include 'altproduct/little-header.html' %}

<section id="account">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">

                <h2 class="section-heading">{{ h2_tag }}</h2>
                <hr class="my-4">

                {% if message %}
                    <p id="error-message">{{ message }}</p>
                {% endif %}
                
                {% for product in alt_products %}
                    <div class="card product-card">
                        <div class="product-card-badge">
                            <span class="product-nutrigrade badge badge-{{ product.nutrigrade }}">{{ product.nutrigrade }}</span>
                        </div>
                        
                        <div class="product-card-img" style="background-image: url({{ product.image }})"></div>
                        
                        <div class="card-body">
                            <h3 class="card-title product-card-title">{{ product.name }}</h3>
                            <a href="{% url 'altproduct:product_detail' product_id=product.id product_name=product.name %}" class="btn btn-primary">Détail du produit</a>
                        </div>

                        {% url 'altproduct:alternative' as alt_url %}
                        {% if user.is_authenticated and request.path == alt_url %}
                            <div class="card-footer" id="fav-product-{{ product.id }}">
                                
                                <i id="fa-{{ product.id }}" class="far fa-check-square"></i>
                                
                                <form id="fav-product-{{ product.id }}-form" class="fav-product-form" method="POST" action="save_product/">
                                    {% csrf_token %}
                                    <input class="save-product" type="submit" value="Sauvegarder ce produit">
                                </form>

                                <script>
                                    $('#fav-product-{{ product.id }}-form').on('submit', function(event){
                                        event.preventDefault();
                                        // Jinja2 variables scope : need to pass them as function parameters to work
                                        var csrf_token = '{{ csrf_token }}';
                                        var product_id = '{{ product.id }}';
                                        var user_id = '{{ user.id }}';
                                        js_save_product(csrf_token, product_id, user_id);
                                    });
                                </script>
                            </div>
                        {% endif %}

                    </div>
                {% endfor %}

                <div class="clearfix"></div>

                {% if paginate %}
                {% url 'altproduct:alternative' as alt_url %}
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if alt_products.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?{% if request.path == alt_url %}produit={{ searched_product }}&{% endif %}page=1">Début</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?{% if request.path == alt_url %}produit={{ searched_product }}&{% endif %}page={{ alt_products.previous_page_number }}" aria-label="Précédent">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Précédent</span>                        
                                </a>
                            </li>
                        {% endif %}
                
                        <li class="page-item page-link disabled">
                        Page {{ alt_products.number }} sur {{ alt_products.paginator.num_pages }}.
                        </li>
                
                        {% if alt_products.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?{% if request.path == alt_url %}produit={{ searched_product }}&{% endif %}page={{ alt_products.next_page_number }}" aria-label="Suivant">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Suivant</span>                    
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?{% if request.path == alt_url %}produit={{ searched_product }}&{% endif %}page={{ alt_products.paginator.num_pages }}">Fin</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}

            </div>
        </div>
    </div>
</section>

{% endblock %}

altproduct/templates/altproduct/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" href="{% static 'altproduct/img/favicon/pur-beurre-favicon.png' %}" />

    <title>Vegalt - Trouver une alternative saine à un produit</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'altproduct/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'altproduct/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="{% static 'altproduct/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'altproduct/css/creative.css' %}" rel="stylesheet">

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'altproduct/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'altproduct/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Ajax script for save product feature -->
    <script src="{% static 'altproduct/js/ajax.js' %}"></script>

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav" style="background-color: #345A61">
      <div class="container">
        <img id="logo" src="{% static 'altproduct/img/logo/pur-beurre.png' %}" title="Pur Beurre" alt="Pur Beurre" />
        <a class="navbar-brand js-scroll-trigger" href="{% url 'altproduct:index' %}">Pur Beurre</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

            <form id="form-search-nav" action="{% url 'altproduct:alternative' %}" method="GET">                    
              {{ search_form.product }}
            </form>

            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'altproduct:account' %}"><i class="fas fa-user"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'altproduct:fav_products' %}"><i class="fas fa-feather-alt"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'altproduct:logout' %}"><i class="fas fa-sign-out-alt"></i></a>
              </li>

            {% else %}
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'altproduct:register' %}">Créer un compte</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'altproduct:account_login' %}">Connexion</a>
              </li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <a href="{% url 'altproduct:legal' %}">Mentions légales</a>
            <a href="{% url 'altproduct:index' %}#contact">Contact</a>
          </div>
        </div>
      </div>
    </footer>

    <!-- Plugin JavaScript -->
    <script src="{% static 'altproduct/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'altproduct/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'altproduct/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'altproduct/js/creative.min.js' %}"></script>

    </body>

</html>

altproduct/templates/altproduct/index.html
{% extends 'altproduct/base.html' %}

{% load static %}

{% block content %}
    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>{{ h1_tag }}</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">Trouvez un produit de subsitution pour ceux que vous consommez tous les jours</p>
            
            <form id="form-search" action="{% url 'altproduct:alternative' %}" method="GET" class="form-inline">                    
              {{ search_form.product }}
              <button type="submit" class="btn btn-primary btn-search">Chercher une alternative</button>
            </form>
            
          </div>
        </div>
      </div>
    </header>

    <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Colette et Rémy</h2>
            <hr class="my-4">
            <p class="text-muted mb-0">Nous sommes une jeune startup fondée par Remy et Colette Tatou, deux restaurateurs de renom. 
              Notre restaurant, situé à Montmartre (Paris), compte une cinquantaine de couverts et ne 
              désemplit pas. Notre spécialité, la ratatouille, nous attire une clientèle internationale 
              charmée par les délices de ce plat typique.</p>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-9 text-center">
            <div class="service-box mt-5 mx-auto">
              <img src="{% static 'altproduct/img/colette.jpg' %}" title="Colette" alt="Colette" />
              <p class="text-muted mb-0 mt-2">Colette</p>
            </div>
          </div>
          <div class="col-lg-6 col-md-9 text-center">
            <div class="service-box mt-5 mx-auto">
              <img src="{% static 'altproduct/img/remy.jpg' %}" title="Rémy" alt="Rémy" />
              <p class="text-muted mb-0 mt-2">Rémy</p>
            </div>
          </div>
    </section>

    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading">Contactez-nous !</h2>
            <hr class="my-4">
            <p class="mb-5">Un produit que vous ne trouvez pas ? Une erreur sur le site constatée ? Une envie de nous dire merci ? N'hésitez pas à nous contacter :)</p>
          
            <p class="mb-5">Par téléphone ou mail :</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fas fa-phone fa-3x mb-3 sr-contact-1"></i>
            <p>12-34-56-67-89</p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fas fa-envelope fa-3x mb-3 sr-contact-2"></i>
            <p class="mb-5">
              <a href="mailto:your-email@your-domain.com">contact@purbeurre.com</a>
            </p>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-lg-8 mx-auto">
                
                <p class="mb-5 text-center">Ou via le formulaire de contact :</p>
                
                <form id="contact-search" action="" method="POST">
                  {% csrf_token %}

                  <div class="fieldWrapper">
                      {{ contact_form.name }}
                  </div>                   
                  <div class="fieldWrapper">
                      {{ contact_form.sender_mail }}
                  </div>      
                  <div class="fieldWrapper" class="form-group">
                      {{ contact_form.message }}
                  </div>      
  
                  <input type="submit" class="btn btn-primary btn-search btn-contact" value="Envoyer">
                </form>
                {% if success %}
                  <p>{{ success }}</p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}